Repository Step3-kakao-tech-campus/Team1_FE, pull requests merged in 2023-10, with the labels that each got.

#21 Feat 가입하기UI
  src/components/atoms/FlexContainer.tsx
  src/components/atoms/HeaderNB/index.tsx
  src/components/atoms/PageContainer.tsx
  src/components/atoms/SubmitButton.tsx
  src/components/organisms/LoginOrSignup.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
  src/styles/index.css
  src/styles/myTheme.ts
  src/styles/reset.css
  src/styles/styled.d.ts
Labels: Status: Reviewing

#22 fix: 그룹 초대장 API 요청 URL 수정
  src/apis/groupInvite.ts
Labels: Type: Bugfix/Function, Priority: high, Status: Reviewing

#23 design 그룹생성페이지 UI 적용
  src/components/atoms/FlexContainer.tsx
  src/pages/AddGroupPage.tsx
Labels: Priority: high, Type: Design, Status: Reviewing

#24 refactor: 중복 제거
  src/App.tsx
  src/components/atoms/BackButton.tsx
  src/components/atoms/CloseButton.tsx
  src/components/atoms/MainContainer.tsx
  src/components/atoms/NextButton.tsx
  src/components/atoms/PageContainer.tsx
  src/components/atoms/PrevButton.tsx
  src/components/atoms/iconButtons/index.tsx
  src/components/molecules/BottomNB.tsx
  src/components/molecules/Dropdown.tsx
  src/components/molecules/HeaderNB.tsx
  src/components/molecules/LoginOrSignup.tsx
  src/components/organisms/Modal.tsx
  src/pages/InvitedPage.tsx
  src/pages/MainPage.tsx
  src/pages/TestPage.tsx
Labels: Priority: high, Type: Refactor, Status: Reviewing

#28 design: 초대링크UI 적용
  src/components/atoms/HeaderNB/index.tsx
  src/components/atoms/InputBox.tsx
  src/components/atoms/modal/index.tsx
  src/hooks/useModal.tsx
  src/pages/InvitedPage.tsx
  src/pages/MainPage.tsx
Labels: Type: Design, Priority: Medium, Status: Reviewing

#32 Fix: 로그인 시 유저 정보를 저장하는 방식 변경
  src/components/molecules/HeaderNB.tsx
  src/hooks/useLogin.ts
  src/states/slices/loginSlice.ts
  src/utils/getInfoByToken.ts
  src/utils/tokenValidator.ts
Labels: Type: Bugfix/Function, Priority: high, Status: Done

#36 Refact: commons
  src/components/@commons/Dropdown.tsx
  src/components/@commons/FlexContainer.tsx
  src/components/@commons/GradationBox.tsx
  src/components/@commons/LoginOrSignup.tsx
  src/components/@commons/PageContainer.tsx
  src/components/@commons/ProfileImage.tsx
  src/components/@commons/SubmitButton.tsx
  src/components/@commons/iconButtons/index.tsx
  src/components/@commons/modal/index.tsx
  src/components/BottomNB/BottomNB.tsx
  src/components/HeaderNB/HeaderNB.tsx
  src/components/HeaderNB/index.tsx
  src/components/atoms/FlexContainer.tsx
  src/hooks/useModal.tsx
  src/pages/AddGroupPage.tsx
  src/pages/InvitedPage.tsx
  src/pages/KakaoAuthPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
Labels: Priority: high, Type: Refactor, Status: Reviewing

#37 Refact: 가입/초대/그룹추가 페이지 리팩토링
  src/components/@commons/GradationBox.tsx
  src/components/@commons/PageContainer.tsx
  src/components/admin-addGroup/AddGroup.tsx
  src/components/admin-addGroup/AddGroupDone.tsx
  src/components/alba-invited/InvitationContent.tsx
  src/components/alba-invited/InvitationTemplate.tsx
  src/components/alba-invited/JoinDone.tsx
  src/components/signup/Addinfo.tsx
  src/components/signup/SelectType.tsx
  src/pages/AddGroupPage.tsx
  src/pages/InvitedPage.tsx
  src/pages/MainPage.tsx
  src/pages/SignupPage.tsx
Labels: Priority: Medium, Type: Refactor, Status: Reviewing

#56 Feat: 매니저 메인페이지
  src/apis/getSch.ts
  src/apis/manageGroup.ts
  src/components/@commons/SubmitButton.tsx
  src/components/@commons/calendar/Calendar.tsx
  src/components/OnBoardingSection.tsx
  src/components/admin-addGroup/AddGroup.tsx
  src/components/admin-home/AdminHomeSection.tsx
  src/components/admin-home/NoGroupSection.tsx
  src/components/alba-invited/InvitationSection.tsx
  src/pages/InvitedPage.tsx
  src/pages/MainPage.tsx
Labels: Type: Feature, Status: Reviewing

#57 Fix : api명세변경
  src/apis/getSch.ts
  src/apis/getSchedule.ts
  src/apis/groupInvite.ts
  src/apis/instance.ts
  src/components/@commons/calendar/Calendar.tsx
  src/components/alba-invited/InvitationContent.tsx
  src/hooks/useLogin.ts
  src/pages/MainPage.tsx
  src/states/slices/loginSlice.ts
Labels: Type: Bugfix/Function, Priority: high, Status: Done

#58 Feat 매니저메인
  package-lock.json
  package.json
  src/App.tsx
  src/apis/getSchedule.ts
  src/apis/instance.ts
  src/auth/HomePrivate.tsx
  src/auth/LogoutOnlyPrivate.tsx
  src/auth/PrivateRoute.tsx
  src/components/@commons-feature/LoginOrSignup.tsx
  src/components/@commons-feature/calendar/Calendar.tsx
  src/components/@commons-feature/calendar/CalendarStyle.tsx
  src/components/@commons-feature/calendar/DailyWorkers.tsx
  src/components/@commons-feature/calendar/NotFixedDateBox.tsx
  src/components/@commons/@Fixing/Dropdown.tsx
  src/components/@commons/FlexContainer.tsx
  src/components/@commons/GrayBox.tsx
  src/components/@commons/PageContainer.tsx
  src/components/@commons/Text.tsx
  src/components/@commons/calendar/Calendar.tsx
  src/components/@commons/iconButtons/index.tsx
  src/components/OnBoardingSection.tsx
  src/components/admin-AddGroupPage/AddGroup.tsx
  src/components/admin-AddGroupPage/AddGroupDone.tsx
  src/components/admin-MainPage/AdminHomePage.tsx
  src/components/admin-MainPage/AdminNoGroupPage.tsx
  src/components/admin-MainPage/AdminNoMemberSection.tsx
  src/components/admin-MainPage/AdminScheduleSection.tsx
  src/components/admin-MainPage/Dropdown.tsx
  src/components/admin-home/AdminHomeSection.tsx
  src/components/admin-home/NoGroupSection.tsx
  src/components/alba-InvitedPage/InvitationContent.tsx
  src/components/alba-InvitedPage/InvitationSection.tsx
  src/components/alba-InvitedPage/JoinDone.tsx
  src/pages/AddGroupPage.tsx
  src/pages/InvitedPage.tsx
  src/pages/MainPage.tsx
  src/pages/OnBoardingPage.tsx
  src/react-app-env.d.ts
  src/styles/myTheme.ts
  src/styles/styled.d.ts
  src/utils/dateToString.ts
Labels: Type: Feature, Status: Done

#63 refactor: 4주차리뷰반영
  src/App.tsx
  src/apis/getSchedule.ts
  src/apis/groupInvite.ts
  src/apis/instance.ts
  src/apis/login.ts
  src/apis/manageGroup.ts
  src/apis/signup.ts
  src/auth/HomePrivate.tsx
  src/components/@commons-feature/calendar/Calendar.tsx
  src/components/@commons-feature/calendar/DailyWorkers.tsx
  src/components/@commons-feature/calendar/DailyWorkersStyle.tsx
  src/components/@commons/GrayBox.tsx
  src/components/@commons/PageContainer.tsx
  src/components/@commons/Text.tsx
  src/components/admin-AddGroupPage/AddGroup.tsx
  src/components/admin-MainPage/AdminHomePage.tsx
  src/components/admin-MainPage/AdminNoMemberSection.tsx
  src/components/admin-MainPage/Dropdown.tsx
  src/components/alba-InvitedPage/InvitationContent.tsx
  src/components/alba-InvitedPage/InvitationSection.tsx
  src/components/signup/Addinfo.tsx
  src/components/signup/SelectType.tsx
  src/hooks/useForm.ts
  src/hooks/useLogin.ts
  src/hooks/useModal.tsx
  src/pages/InvitedPage.tsx
  src/pages/SignupPage.tsx
  src/styles/index.css
  src/styles/reset.css
  src/utils/signupValidator.ts
Labels: Type: Refactor, Status: Done

#68 Feat #38 초대링크발급
  package-lock.json
  package.json
  src/apis/groupInvite.ts
  src/components/@commons/modal/index.tsx
  src/components/admin-etc/GetInviteKey.tsx
  src/components/alba-InvitedPage/InvitationContent.tsx
  src/components/alba-InvitedPage/InvitationSection.tsx
Labels: Type: Feature, Status: Done

#70 Feat #49 주차선택
  src/App.tsx
  src/apis/getApplyStatus.ts
  src/apis/getSchedule.ts
  src/apis/getWeekProgress.ts
  src/auth/AdminHasGroupPrivate.tsx
  src/auth/AdminOnlyPrivate.tsx
  src/components/@commons-feature/calendar/Calendar.tsx
  src/components/@commons-feature/calendar/CalendarStyle.tsx
  src/components/@commons-feature/calendar/CalenderOutter.tsx
  src/components/@commons-feature/calendar/DailyWorkers.tsx
  src/components/@commons-feature/calendar/DailyWorkersTemplate.tsx
  src/components/BottomNB/BottomNB.tsx
  src/hooks/useWeekSelector.tsx
  src/pages/HomePage.tsx
  src/pages/admin-MainPage/AdminHomePage.tsx
  src/pages/admin-MainPage/AdminScheduleSection.tsx
  src/pages/admin-MainPage/SchedulePage/AdminScheduleSection.tsx
  src/pages/admin-MainPage/SchedulePage/Dropdown.tsx
  src/pages/admin-MainPage/SchedulePage/FixedDailyBox.tsx
  src/pages/admin-MainPage/SchedulePage/FixedMonthlyConents.tsx
  src/pages/admin-SelectWeekPage/MonthlyContents.tsx
  src/pages/admin-SelectWeekPage/SelectWeekPage.tsx
  src/pages/admin-SelectWeekPage/WeekBoxContents.tsx
  src/pages/admin-SelectWeekPage/WeeklyDatail.tsx
  src/styles/myTheme.ts
  src/styles/styled.d.ts
  src/utils/weekdayArray.ts
Labels: Priority: high, Type: Feature, Status: Reviewing

#65 부산대_1조_스케줄알빠임_5주차
  package-lock.json
  package.json
  src/App.tsx
  src/apis/getSchedule.ts
  src/apis/instance.ts
  src/auth/HomePrivate.tsx
  src/auth/LogoutOnlyPrivate.tsx
  src/auth/PrivateRoute.tsx
  src/components/@commons-feature/LoginOrSignup.tsx
  src/components/@commons-feature/calendar/Calendar.tsx
  src/components/@commons-feature/calendar/CalendarStyle.tsx
  src/components/@commons-feature/calendar/DailyWorkers.tsx
  src/components/@commons-feature/calendar/NotFixedDateBox.tsx
  src/components/@commons/@Fixing/Dropdown.tsx
  src/components/@commons/FlexContainer.tsx
  src/components/@commons/GrayBox.tsx
  src/components/@commons/PageContainer.tsx
  src/components/@commons/Text.tsx
  src/components/@commons/calendar/Calendar.tsx
  src/components/@commons/iconButtons/index.tsx
  src/components/OnBoardingSection.tsx
  src/components/admin-AddGroupPage/AddGroup.tsx
  src/components/admin-AddGroupPage/AddGroupDone.tsx
  src/components/admin-MainPage/AdminHomePage.tsx
  src/components/admin-MainPage/AdminNoGroupPage.tsx
  src/components/admin-MainPage/AdminNoMemberSection.tsx
  src/components/admin-MainPage/AdminScheduleSection.tsx
  src/components/admin-MainPage/Dropdown.tsx
  src/components/admin-home/AdminHomeSection.tsx
  src/components/admin-home/NoGroupSection.tsx
  src/components/alba-InvitedPage/InvitationContent.tsx
  src/components/alba-InvitedPage/InvitationSection.tsx
  src/components/alba-InvitedPage/JoinDone.tsx
  src/pages/AddGroupPage.tsx
  src/pages/InvitedPage.tsx
  src/pages/MainPage.tsx
  src/pages/OnBoardingPage.tsx
  src/react-app-env.d.ts
  src/styles/myTheme.ts
  src/styles/styled.d.ts
  src/utils/dateToString.ts
Labels: Type: Request Review

#78 Feat #47 모집시작
  src/App.tsx
  src/apis/adminApplication.ts
  src/apis/getApplyStatus.ts
  src/components/@commons-feature/calendar/CalenderOutter.tsx
  src/components/@commons/ColorBox.tsx
  src/components/@commons/FlexContainer.tsx
  src/components/@commons/Text.tsx
  src/components/@commons/iconButtons/index.tsx
  src/components/admin-ApplicationOpenPage/setPeople/index.tsx
  src/components/admin-ApplicationOpenPage/setTime/index.tsx
  src/components/admin-etc/GetInviteKey.tsx
  src/hooks/admin-ApplicationOpenPage/usePeopleAmount.ts
  src/hooks/admin-ApplicationOpenPage/useTimeTemplate.ts
  src/pages/admin-AddGroupPage/AddGroupDone.tsx
  src/pages/admin-ApplicationOpenPage/ApplicationOpenPage.tsx
  src/pages/admin-ApplicationOpenPage/SetPeopleSection.tsx
  src/pages/admin-ApplicationOpenPage/SetTimeSection.tsx
  src/pages/admin-ApplicationOpenPage/SetTimeTemplate.tsx
  src/pages/admin-MainPage/AdminNoGroupPage.tsx
  src/pages/admin-MainPage/SchedulePage/Dropdown.tsx
  src/pages/admin-MainPage/SchedulePage/TotalWorkTime.tsx
  src/pages/admin-SelectWeekPage/MonthlyContents.tsx
  src/pages/admin-SelectWeekPage/SelectWeekPage.tsx
  src/pages/admin-SelectWeekPage/WeeklyDatail.tsx
  src/pages/alba-InvitedPage/InvitationContent.tsx
Labels: Type: Feature, Status: Done

#88 Feat #48 모집마감
  src/App.tsx
  src/apis/adminApplication.ts
  src/components/@commons-feature/calendar/DailyWorkersTemplate.tsx
  src/components/@commons/FlexContainer.tsx
  src/components/PageStyledComponents/admin-ApplicationClose/index.tsx
  src/components/PageStyledComponents/admin-ApplicationOpenPage/setPeople/index.tsx
  src/components/PageStyledComponents/admin-ApplicationOpenPage/setTime/index.tsx
  src/components/PageStyledComponents/admin-SchedulePage/Dropdown/index.tsx
  src/components/PageStyledComponents/admin-etc/GetInviteKey.tsx
  src/hooks/admin-ApplicationClosePage/useClose.ts
  src/pages/admin-ApplicationClosePage/ApplicationClosePage.tsx
  src/pages/admin-ApplicationClosePage/SelectRecommendsSection.tsx
  src/pages/admin-ApplicationOpenPage/SetPeopleSection.tsx
  src/pages/admin-ApplicationOpenPage/SetTimeTemplate.tsx
  src/pages/admin-MainPage/SchedulePage/AdminScheduleSection.tsx
  src/pages/admin-MainPage/SchedulePage/Dropdown.tsx
  src/pages/admin-MainPage/SchedulePage/FixedDailyBox.tsx
  src/styles/index.css
  src/utils/stringDateMove.ts
Labels: Type: Feature, Status: Done

#90 Refactor #89 5주차 코드리뷰반영
  src/App.tsx
  src/auth/AdminHasGroupPrivate.tsx
  src/auth/AdminOnlyPrivate.tsx
  src/auth/LogoutOnlyPrivate.tsx
  src/components/@commons/ColorBox.tsx
  src/components/@commons/FlexContainer.tsx
  src/components/@commons/GrayBox.tsx
  src/components/HeaderNB/HeaderNB.tsx
  src/hooks/useLogin.ts
  src/pages/HomePage.tsx
  src/pages/admin-MainPage/AdminHomePage.tsx
  src/pages/admin-MainPage/AdminNoGroupPage.tsx
  src/pages/admin-MainPage/AdminNoGroupSection.tsx
  src/pages/admin-MainPage/SchedulePage/AdminScheduleSection.tsx
  src/pages/admin-MainPage/SchedulePage/FixedDailyBox.tsx
  src/pages/alba-InvitedPage/InvitationSection.tsx
Labels: Type: Refactor, Status: Done

#94 Feat #51 알바하단바
  src/components/@commons/PageContainer.tsx
  src/components/@commons/modal/index.tsx
  src/components/BottomNB/BottomNB.tsx
  src/components/BottomNB/Icons.tsx
  src/hooks/useModal.tsx
Labels: Type: Feature, Status: Done

#72 Feat 사이드바
  src/components/@commons/FlexContainer.tsx
  src/components/@commons/sidebar/Sidebar.tsx
  src/components/@commons/sidebar/index.tsx
  src/components/HeaderNB/HeaderNB.tsx
Labels: Type: Feature, Priority: Medium, Status: Reviewing

#96 Refactor #95 사이드바수정
  src/components/@commons/modal/index.tsx
  src/components/@commons/sidebar/Sidebar.tsx
  src/components/BottomNB/BottomNBStyles.tsx
  src/components/HeaderNB/HeaderNB.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/index.tsx
Labels: Type: Bugfix/Function, Status: Done

#104 Feat #44 스케줄신청
  .gitignore
  Dockerfile
  k8s/deployment.yaml
  k8s/ingress.yaml
  k8s/kustomization.yaml
  k8s/service.yaml
  src/App.tsx
  src/apis/admin/application/index.ts
  src/apis/alba/apply/index.ts
  src/components/@commons/BorderBox.tsx
  src/components/@commons/CheckBox.tsx
  src/components/@commons/GradationBox.tsx
  src/components/BottomNB/BottomNB.tsx
  src/components/Calendar/CalendarStyle.tsx
  src/hooks/alba/useApply.ts
  src/hooks/useLogin.ts
  src/pages/SchedulePage/CalendarSection/CalendarDayBox.tsx
  src/pages/SelectWeekPage/AdminDetailSection/ClosedDetail.tsx
  src/pages/SelectWeekPage/AdminDetailSection/InProgressDetail.tsx
  src/pages/SelectWeekPage/AdminDetailSection/OpenDetail.tsx
  src/pages/SelectWeekPage/AdminDetailSection/index.tsx
  src/pages/SelectWeekPage/AlbaSubmitButton/index.tsx
  src/pages/SelectWeekPage/Calendar/StatusCalendar.tsx
  src/pages/SelectWeekPage/Calendar/StatusDailyBox.tsx
  src/pages/SelectWeekPage/index.tsx
  src/pages/SignupPage/AddinfoSection/index.tsx
  src/pages/admin/AddGroupPage/FormSection/index.tsx
  src/pages/admin/ApplicationOpenPage/SetPeopleSection/index.tsx
  src/pages/admin/ApplicationOpenPage/SetTimeTemplateSection/EditTimeForm.tsx
  src/pages/admin/ApplicationOpenPage/index.tsx
  src/pages/admin/ETCMainPage/index.tsx
  src/pages/alba/AlbaMainIndex.tsx
  src/pages/alba/ApplyPage/PreviewSection/index.tsx
  src/pages/alba/ApplyPage/TimeSelectSection/DailySelect.tsx
  src/pages/alba/ApplyPage/TimeSelectSection/index.tsx
  src/pages/alba/ApplyPage/index.tsx
  src/privateRoutes/UserTypePrivate.tsx
  src/react-app-env.d.ts
  src/utils/stringDateMove.ts
Labels: Type: Feature, Status: in Progress

#108 Feat #107 메인기능세부
  .gitignore
  k8s/configMap.yaml
  k8s/deployment.yaml
  k8s/kustomization.yaml
  package-lock.json
  package.json
  src/App.tsx
  src/apis/schedule/getMonthly.ts
  src/apis/types.ts
  src/components/@commons/GrayBox.tsx
  src/components/@commons/SubmitButton.tsx
  src/components/Calendar/CalenderOutter.tsx
  src/components/HeaderNB/HeaderNB.tsx
  src/components/HeaderNB/HeaderNBStyels.tsx
  src/components/HeaderNB/icons.tsx
  src/components/PageStyledComponents/admin/AddGroup/index.tsx
  src/components/Sidebar/Sidebar.tsx
  src/error/ErrorFallback.tsx
  src/error/ErrorPage.tsx
  src/error/useErrorHandler.ts
  src/hooks/SchedulePage/useSchedule.ts
  src/hooks/admin/ApplicationClosePage/useClose.ts
  src/hooks/admin/ApplicationOpenPage/usePeopleAmount.ts
  src/hooks/admin/ApplicationOpenPage/useTimeTemplate.ts
  src/hooks/alba/useApply.ts
  src/hooks/useForm.ts
  src/hooks/useLogin.ts
  src/pages/SchedulePage/HeaderSection/Dropdown.tsx
  src/pages/SchedulePage/HeaderSection/TotalWorkTime.tsx
  src/pages/SchedulePage/index.tsx
  src/pages/SchedulePage/states.ts
  src/pages/SignupPage/AddinfoSection/index.tsx
  src/pages/SignupPage/SelectTypeSection/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/admin/AddGroupPage/FormSection/InputBar.tsx
  src/pages/admin/AddGroupPage/FormSection/index.tsx
  src/pages/admin/AddGroupPage/index.tsx
  src/pages/admin/ApplicationClosePage/SelectRecommendsSection/index.tsx
  src/pages/admin/ApplicationOpenPage/SetPeopleSection/EditAmountForm.tsx
  src/pages/admin/ApplicationOpenPage/SetPeopleSection/index.tsx
  src/pages/admin/ApplicationOpenPage/SetTimeTemplateSection/index.tsx
  src/pages/admin/ETCMainPage/index.tsx
  src/pages/alba/AlbaMainIndex.tsx
  src/pages/alba/ApplyPage/PreviewSection/index.tsx
  src/pages/alba/ApplyPage/TimeSelectSection/index.tsx
  src/pages/alba/InvitedPage/InvitationSection.tsx
  src/utils/signupValidator.ts
  src/utils/stringDateMove.ts
  src/utils/tokenValidator.ts
  src/utils/validators.ts
Labels: Priority: high, Type: Feature, Status: Done

#117 refactor: 코드리뷰 반영 #116
  src/components/Calendar/CalenderOutter.tsx
  src/components/modals/GetInviteKey/index.tsx
  src/error/ErrorFallback.tsx
  src/error/useErrorHandler.ts
  src/hooks/SchedulePage/useSchedule.ts
  src/hooks/admin/ApplicationClosePage/useClose.ts
  src/hooks/admin/ApplicationOpenPage/usePeopleAmount.ts
  src/hooks/admin/ApplicationOpenPage/usePeopleValidation.ts
  src/hooks/admin/ApplicationOpenPage/useTimeTemplate.ts
  src/hooks/alba/useApply.ts
  src/hooks/useModal.tsx
  src/hooks/useWeekSelector.tsx
  src/pages/SchedulePage/CalendarSection/CalendarDayBox.tsx
  src/pages/SchedulePage/DailyWorkerSection/DailyWorkers.tsx
  src/pages/SchedulePage/index.tsx
  src/pages/SchedulePage/states.ts
  src/pages/SelectWeekPage/AdminDetailSection/ClosedDetail.tsx
  src/pages/SelectWeekPage/Calendar/StatusCalendar.tsx
  src/pages/SelectWeekPage/Calendar/StatusDailyBox.tsx
  src/pages/SelectWeekPage/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/admin/AddGroupPage/DoneSection/index.tsx
  src/pages/admin/AddGroupPage/index.tsx
  src/pages/admin/AdminMainIndex.tsx
  src/pages/admin/ApplicationClosePage/SelectRecommendsSection/index.tsx
  src/pages/admin/ApplicationOpenPage/SetPeopleSection/EditAmountForm.tsx
  src/pages/admin/ApplicationOpenPage/SetPeopleSection/index.tsx
  src/pages/admin/ApplicationOpenPage/SetTimeTemplateSection/EditTimeForm.tsx
  src/pages/admin/ApplicationOpenPage/index.tsx
  src/pages/admin/ETCMainPage/index.tsx
  src/pages/alba/AlbaMainIndex.tsx
  src/pages/alba/ApplyPage/PreviewSection/index.tsx
  src/pages/alba/ApplyPage/TimeSelectSection/DailySelect.tsx
  src/pages/alba/ApplyPage/TimeSelectSection/index.tsx
  src/pages/alba/ApplyPage/index.tsx
  src/pages/alba/InvitedPage/JoinDone.tsx
  src/pages/alba/InvitedPage/index.tsx
  src/utils/dateToString.ts
  src/utils/stringDateMove.ts
Labels: Type: Refactor, Status: Done

#120 Refactor #119 기능7수정
  src/apis/admin/application/open/index.ts
  src/apis/admin/application/status/index.ts
  src/apis/alba/apply/index.ts
  src/apis/schedule/getDailyWorkers.ts
  src/apis/types.ts
  src/components/@commons/PopUpPage.tsx
  src/components/DailyWorkers/DailyWorkersTemplate.tsx
  src/hooks/usePopUpPage.tsx
  src/pages/SchedulePage/CalendarSection/CalendarDayBox.tsx
  src/pages/SchedulePage/DailyWorkerSection/DailyWorkers.tsx
  src/pages/SchedulePage/states.ts
  src/pages/SelectWeekPage/AdminDetailSection/ClosedDetail.tsx
  src/pages/SelectWeekPage/AdminDetailSection/InProgressDetail.tsx
  src/pages/SignupPage/SelectTypeSection/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/alba/ApplyPage/index.tsx
  src/utils/loginDatahandlers.ts
  src/utils/strTimeProcessor.ts
  src/utils/validators.ts
Labels: Type: Bugfix/Function, Priority: high, Status: Done

#122 Refactor #121 모바일최적화
  src/components/@commons/PageContainer.tsx
  src/components/@commons/Text.tsx
  src/components/@commons/ViewPortContainer.tsx
  src/components/BottomNB/BottomNBStyles.tsx
  src/components/Calendar/CalendarStyle.tsx
  src/components/HeaderNB/HeaderNBStyels.tsx
  src/components/PageStyledComponents/admin/SelectWeekPage/index.tsx
  src/components/modals/index.tsx
  src/hooks/useWeekSelector.tsx
  src/pages/SelectWeekPage/Calendar/StatusCalendar.tsx
  src/setupTests.ts
  src/styles/index.css
  src/styles/myTheme.ts
  src/styles/styled.d.ts
Labels: Priority: high, Type: Design, Status: Done

#127 Refactor #125 관심사분리
  public/index.html
  src/apis/admin/manageGroup/index.ts
  src/apis/alba/apply/index.ts
  src/apis/instance.ts
  src/apis/types.ts
  src/assets/schedule_albbaim.png
  src/components/@commons/FlexContainer.tsx
  src/components/@commons/LogoPicture.tsx
  src/components/@commons/PopUpPage.tsx
  src/components/@commons/ViewPortContainer.tsx
  src/components/@commons/iconButtons/index.tsx
  src/hooks/SchedulePage/fetch.ts
  src/hooks/SchedulePage/useSchedule.ts
  src/hooks/SelectWeekPage/fetch.ts
  src/hooks/SelectWeekPage/useSelectWeek.ts
  src/hooks/SelectWeekPage/useWeeklyDetail.ts
  src/hooks/SignUpPage/useSignUpForm.ts
  src/hooks/admin/AddGroupPage/useAddGroupForm.tsx
  src/hooks/admin/ApplicationClosePage/fetch.ts
  src/hooks/admin/ApplicationClosePage/useClose.ts
  src/hooks/alba/apply/fetch.ts
  src/hooks/alba/apply/usePreviewSelected.ts
  src/hooks/alba/apply/useSelectTime.ts
  src/hooks/alba/useApply.ts
  src/pages/KakaoAuthPage.tsx
  src/pages/OnBoardingPage.tsx
  src/pages/SchedulePage/CalendarSection/CalendarDayBox.tsx
  src/pages/SchedulePage/CalendarSection/CalenderConents.tsx
  src/pages/SchedulePage/DailyWorkerSection/DailyWorkers.tsx
  src/pages/SelectWeekPage/AdminDetailSection/ClosedDetail.tsx
  src/pages/SelectWeekPage/AdminDetailSection/InProgressDetail.tsx
  src/pages/SelectWeekPage/AdminDetailSection/OpenDetail.tsx
  src/pages/SelectWeekPage/AdminDetailSection/index.tsx
  src/pages/SelectWeekPage/AlbaSubmitButton/index.tsx
  src/pages/SelectWeekPage/Calendar/StatusCalendar.tsx
  src/pages/SelectWeekPage/index.tsx
  src/pages/SelectWeekPage/states.ts
  src/pages/SignupPage/AddinfoSection/index.tsx
  src/pages/SignupPage/SelectTypeSection/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/admin/AddGroupPage/AddGroupDonePopUp/index.tsx
  src/pages/admin/AddGroupPage/FormSection/InputBar.tsx
  src/pages/admin/AddGroupPage/FormSection/index.tsx
  src/pages/admin/AddGroupPage/index.tsx
  src/pages/admin/ApplicationClosePage/SelectRecommendsSection/index.tsx
  src/pages/alba/ApplyPage/PreviewSection/index.tsx
  src/pages/alba/ApplyPage/TimeSelectSection/DailySelect.tsx
  src/styles/fonts/Pretendard-Bold.woff2
  src/styles/fonts/Pretendard-ExtraBold.woff2
  src/styles/fonts/Pretendard-ExtraLight.woff2
  src/styles/fonts/Pretendard-Light.woff2
  src/styles/fonts/Pretendard-Medium.woff2
  src/styles/fonts/Pretendard-Regular.woff2
  src/styles/fonts/Pretendard-SemiBold.woff2
Labels: Type: Refactor, Status: Done

#128 Refactor #123 성능최적화
  package.json
  src/components/@commons/Text.tsx
  src/components/@commons/iconButtons/index.tsx
  src/components/@commons/icons/buttons.tsx
  src/components/@commons/icons/index.tsx
  src/components/Calendar/CalenderOutter.tsx
  src/components/HeaderNB/HeaderNB.tsx
  src/components/HeaderNB/HeaderNBStyels.tsx
  src/components/HeaderNB/icons.tsx
  src/components/PageStyledComponents/admin/AddGroup/index.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/index.tsx
  src/components/Sidebar/styles.tsx
  src/hooks/admin/AddGroupPage/useAddGroupForm.tsx
  src/pages/SchedulePage/HeaderSection/Dropdown.tsx
  src/pages/SchedulePage/HeaderSection/TotalWorkTime.tsx
  src/pages/SchedulePage/index.tsx
  src/pages/SignupPage/index.tsx
  src/pages/admin/AddGroupPage/FormSection/InputBar.tsx
  src/pages/admin/ApplicationOpenPage/SetTimeTemplateSection/EditTimeForm.tsx
  src/styles/index.css
  src/styles/myTheme.ts
  src/styles/styled.d.ts
Labels: Priority: high, Type: Refactor, Status: Done

#129 Feat #66 시간대컬러
  Dockerfile
  package-lock.json
  src/apis/convertURI.ts
  src/apis/schedule/getMonthly.ts
  src/components/@commons/PageContainer.tsx
  src/components/@commons/ViewPortContainer.tsx
  src/components/Calendar/CalendarStyle.tsx
  src/components/Calendar/CalenderOutter.tsx
  src/components/DailyWorkers/DailyWorkersStyle.tsx
  src/components/DailyWorkers/DailyWorkersTemplate.tsx
  src/components/PageStyledComponents/admin/MainPage/index.tsx
  src/components/Sidebar/index.tsx
  src/hooks/SchedulePage/fetch.ts
  src/hooks/alba/apply/fetch.ts
  src/hooks/useGetMyInfo.ts
  src/pages/SchedulePage/CalendarSection/CalendarDayBox.tsx
  src/pages/SchedulePage/CalendarSection/CalenderConents.tsx
  src/pages/SchedulePage/DailyWorkerSection/DailyWorkers.tsx
  src/pages/SchedulePage/HeaderSection/Dropdown.tsx
  src/pages/SchedulePage/HeaderSection/TotalWorkTime.tsx
  src/pages/SchedulePage/index.tsx
  src/pages/SelectWeekPage/Calendar/StatusCalendar.tsx
  src/pages/SelectWeekPage/Calendar/StatusCalendarWeekly.tsx
  src/pages/SelectWeekPage/Calendar/StatusDailyBox.tsx
  src/pages/SelectWeekPage/index.tsx
  src/pages/admin/AddGroupPage/index.tsx
  src/pages/admin/AdminMainIndex.tsx
  src/pages/alba/AlbaMainIndex.tsx
  src/pages/alba/InvitedPage/InvitationContent.tsx
  src/styles/myTheme.ts
  src/styles/styled.d.ts
  src/utils/colors.ts
Labels: Type: Feature, Status: in Progress
